# -*- coding: utf-8 -*-
"""M H Nithya Shree -  AI Engineer Role - Case Study Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMuLYJZM16X6FWOPLSwZxu3oevmeXT3q

Self-Pruning Neural Network for CIFAR-10
=========================================
Tredence AI Engineering Internship – Case Study Solution

This is the implementation of a feedforward neural network where each weight has
an associated learnable "gate" parameter. During training, L1 regularisation
on the sigmoid-activated gate scores drives many gates toward zero, effectively
pruning those connections without any post-training step.

Author : M H NITHYA SHREE
Date   : 21-04-2026
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

# 1.  Custom Layer: PrunableLinear
"""
    A drop-in replacement for nn.Linear that pairs every weight scalar
    with a learnable gate_score.

    Forward pass:
        gates         = sigmoid(gate_scores)          ∈ (0, 1)
        pruned_weights = weight * gates               element-wise
        output        = pruned_weights @ x.T + bias   standard linear op

    Why sigmoid?
        Sigmoid squashes gate_scores to (0, 1), bounding the gate values so
        the L1 penalty has a well-defined scale.  Values near 0 mean the
        weight is "switched off"; values near 1 mean it is fully active.

    Gradient flow:
        Both weight and gate_scores receive gradients automatically because
        pruned_weights = weight * sigmoid(gate_scores) is a differentiable
        expression in both leaf tensors.
    """
class PrunableLinear(nn.Module):

    def __init__(self, in_features: int, out_features: int):
        super().__init__()

        # Standard learnable weight and bias
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias   = nn.Parameter(torch.zeros(out_features))

        # Gate scores – same shape as weight, also updated by the optimiser
        self.gate_scores = nn.Parameter(torch.empty(out_features, in_features))

        # Initialise weights with Kaiming uniform (good default for ReLU nets)
        nn.init.kaiming_uniform_(self.weight, nonlinearity='relu')
        # Initialise gate_scores near zero so sigmoid(0)=0.5 – gates start half-open
        nn.init.constant_(self.gate_scores, -3.0)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Step 1: convert scores to gates in (0, 1)
        gates = torch.sigmoid(self.gate_scores)

        # Step 2: mask weights – if gate→0, the weight contributes nothing
        pruned_weights = self.weight * gates

        # Step 3: standard linear operation using masked weights
        return F.linear(x, pruned_weights, self.bias)

    def get_gates(self) -> torch.Tensor:
        """Return gate values (detached) for analysis."""
        return torch.sigmoid(self.gate_scores).detach()

# 2.  Model Architecture
class SelfPruningNet(nn.Module):
    """
    Three-hidden-layer feedforward network built with PrunableLinear layers.

    CIFAR-10 images are 32×32×3 = 3 072 raw pixels.
    We flatten them and pass through hidden layers of diminishing width.
    ReLU activations add non-linearity between every layer.

    Architecture:
        3072  →  512  →  256  →  128  →  10
    """

    def __init__(self):
        super().__init__()

        self.fc1 = PrunableLinear(3072, 512)
        self.fc2 = PrunableLinear(512,  256)
        self.fc3 = PrunableLinear(256,  128)
        self.fc4 = PrunableLinear(128,   10)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.view(x.size(0), -1)       # flatten: (B, 3, 32, 32) → (B, 3072)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)                  # logits – no activation before CrossEntropy
        return x

    def prunable_layers(self):
        """Yield all PrunableLinear sub-modules for convenient iteration."""
        for m in self.modules():
            if isinstance(m, PrunableLinear):
                yield m

# 3.  Loss Function

def sparsity_loss(model: SelfPruningNet) -> torch.Tensor:
    return sum(
        torch.sigmoid(layer.gate_scores).sum()
        for layer in model.prunable_layers()
    )

def total_loss(
    logits: torch.Tensor,
    labels: torch.Tensor,
    model: SelfPruningNet,
    lam: float,
) -> torch.Tensor:
    """
    Total Loss = CrossEntropy(logits, labels)  +  λ × SparsityLoss

    λ (lambda) is the trade-off hyperparameter:
      - Small λ  → almost no pruning pressure; model retains accuracy.
      - Large λ  → heavy pruning pressure; many gates collapse to 0.
    """
    cls_loss = F.cross_entropy(logits, labels)
    spar_loss = sparsity_loss(model)
    return cls_loss + lam * spar_loss

# 4.  Dataset Loading

def get_cifar10_loaders(batch_size: int = 256):
    """
    Download CIFAR-10 and return train / test DataLoaders.

    """
    mean = (0.4914, 0.4822, 0.4465)
    std  = (0.2470, 0.2435, 0.2616)

    train_transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),       # light augmentation
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])
    test_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])

    train_set = torchvision.datasets.CIFAR10(
        root='./data', train=True,  download=True, transform=train_transform
    )
    test_set  = torchvision.datasets.CIFAR10(
        root='./data', train=False, download=True, transform=test_transform
    )

    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True,
                              num_workers=0, pin_memory=True)
    test_loader  = DataLoader(test_set,  batch_size=batch_size, shuffle=False,
                              num_workers=0, pin_memory=True)
    return train_loader, test_loader

# 5.  Training Loop

def train(
    model: SelfPruningNet,
    loader: DataLoader,
    optimizer: optim.Optimizer,
    device: torch.device,
    lam: float,
) -> float:
    """
    One epoch of training.  Returns average loss over all batches.

    Adam is used because:
      - It adapts the learning rate per parameter (helpful when gate_scores
        and weight tensors have very different gradient magnitudes).
      - It is robust to hyperparameter choice – less tuning needed.
    """
    model.train()
    running_loss = 0.0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        logits = model(images)
        loss   = total_loss(logits, labels, model, lam)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

    return running_loss / len(loader.dataset)

# 6.  Evaluation Loop

def evaluate(
    model: SelfPruningNet,
    loader: DataLoader,
    device: torch.device,
) -> float:
    """Return top-1 accuracy (%) on the given DataLoader."""
    model.eval()
    correct = 0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            logits = model(images)
            preds  = logits.argmax(dim=1)
            correct += (preds == labels).sum().item()

    return 100.0 * correct / len(loader.dataset)

def evaluate_hard_pruned(model, loader, device, threshold=1e-2):
    """
    Zero out all gates below threshold and re-evaluate.
    This simulates actual inference-time pruning — the model
    with dead weights literally removed, not just suppressed.
    """
    # Hard zero all gates below threshold
    with torch.no_grad():
        for layer in model.prunable_layers():
            mask = layer.get_gates() < threshold
            layer.gate_scores[mask] = -1e9  # forces sigmoid → ~0

    return evaluate(model, loader, device)

# 7.  Sparsity Computation

def compute_sparsity(model: SelfPruningNet, threshold: float = 1e-2) -> float:
    """
    Sparsity = percentage of gates below *threshold*.

    A threshold of 1e-2 (0.01) is used because:
      - sigmoid(−5) ≈ 0.007, so any gate_score driven below roughly −5
        produces a gate value that is negligibly small for practical purposes.
      - 1e-2 is a natural, interpretable cutoff for "effectively zero."
    """
    all_gates   = torch.cat([
        layer.get_gates().flatten() for layer in model.prunable_layers()
    ])
    pruned      = (all_gates < threshold).sum().item()
    return 100.0 * pruned / all_gates.numel()


def all_gate_values(model: SelfPruningNet) -> np.ndarray:
    """Return all gate values as a 1-D numpy array (for plotting)."""
    return torch.cat([
        layer.get_gates().flatten() for layer in model.prunable_layers()
    ]).cpu().numpy()

# 8.  Visualisation

def plot_gate_histogram(gates: np.ndarray, lam: float, save_path: str = None):
    """
    Histogram of final gate values.

    A successful pruning run shows:
      - A large spike at 0  (pruned, inactive connections)
      - A smaller cluster near 1  (active, important connections)
    The bimodal distribution is the hallmark of effective gate-based pruning.
    """
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(gates, bins=100, color='steelblue', edgecolor='white', linewidth=0.4)
    ax.set_title(f'Gate Value Distribution  (λ = {lam})', fontsize=14, fontweight='bold')
    ax.set_xlabel('Gate Value  (sigmoid output ∈ (0, 1))', fontsize=12)
    ax.set_ylabel('Count', fontsize=12)
    ax.axvline(x=0.01, color='crimson', linestyle='--', linewidth=1.4,
               label='Sparsity threshold (0.01)')
    ax.legend(fontsize=10)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150)
        print(f"  Plot saved → {save_path}")
    plt.show()

# 9.  Experiment Runner

def run_experiment(lam: float, epochs: int, device: torch.device,
                   train_loader, test_loader) -> dict:
    """Train a fresh model for a single λ value and return metrics."""
    print(f"\n{'='*60}")
    print(f"  λ = {lam}   |   Epochs = {epochs}")
    print(f"{'='*60}")

    model     = SelfPruningNet().to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=0.0)

    for epoch in range(1, epochs + 1):
        avg_loss = train(model, train_loader, optimizer, device, lam)
        if epoch % 5 == 0 or epoch == 1:
            acc = evaluate(model, test_loader, device)
            sp  = compute_sparsity(model)
            print(f"  Epoch {epoch:3d}/{epochs}  |  Loss: {avg_loss:.4f}  "
                  f"|  Test Acc: {acc:.2f}%  |  Sparsity: {sp:.1f}%")

    final_acc      = evaluate(model, test_loader, device)
    final_sparsity = compute_sparsity(model)
    gates          = all_gate_values(model)
    hard_acc = evaluate_hard_pruned(model, test_loader, device)

    print(f"\n  ✓ Final Test Accuracy : {final_acc:.2f}%")
    print(f"  ✓ Final Sparsity      : {final_sparsity:.1f}%")
    print(f"  ✓ Hard-Pruned Accuracy : {hard_acc:.2f}%")

    return {
        'lam':      lam,
        'accuracy': final_acc,
        'sparsity': final_sparsity,
        'gates':    gates,
        'model':    model,
    }

# 10.  Main

def main():
    # ── Configuration ──────────────────────────────────────────────────────
    EPOCHS     = 30
    BATCH_SIZE = 256
    LAMBDAS    = [1e-5, 1e-4, 1e-3]   # low, medium, high sparsity pressure
    THRESHOLD  = 1e-2
    DEVICE     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"Device : {DEVICE}")

    # ── Data ───────────────────────────────────────────────────────────────
    train_loader, test_loader = get_cifar10_loaders(batch_size=BATCH_SIZE)

    # ── Run experiments for each λ ─────────────────────────────────────────
    results = []
    for lam in LAMBDAS:
        res = run_experiment(lam, EPOCHS, DEVICE, train_loader, test_loader)
        results.append(res)

    # ── Summary table ──────────────────────────────────────────────────────
    print("\n" + "="*55)
    print(f"  {'Lambda':<12}  {'Test Accuracy':>15}  {'Sparsity %':>12}")
    print("="*55)
    for r in results:
        print(f"  {r['lam']:<12}  {r['accuracy']:>14.2f}%  {r['sparsity']:>11.1f}%")
    print("="*55)

    # ── Plot gate histograms ────────────────────────────────────────────────
    for r in results:
        plot_gate_histogram(
            r['gates'], r['lam'],
            save_path=f"gate_hist_lambda_{r['lam']}.png"
        )

main()
